export const eventTypes = [
    { id: "1", en: "Four evenings' walk", it: "Camminata di 4 giorni" },
    { id: "2", en: "Company outing", it: "Gita aziendale" },
    { id: "56", en: "Company party", it: "Festa aziendale" },
    { id: "3", en: "Fair (exhibitor)", it: "Fiera (espositore)" },
    { id: "4", en: "Fair (organiser)", it: "Fiera (organizzatore)" },
    { id: "5", en: "Flower parade", it: "Sfilata di fiori" },
    { id: "6", en: "Street fair", it: "Fiera di strada" },
    { id: "7", en: "Neighbourhood party", it: "Festa di quartiere" },
    { id: "8", en: "Wedding", it: "Matrimonio" },
    { id: "9", en: "Carnival (party/procession)", it: "Carnevale (festa/sfilata)" },
    { id: "10", en: "Colour run", it: "Corsa dei colori" },
    { id: "11", en: "Concert", it: "Concerto" },
    { id: "12", en: "Conference", it: "Conferenza" },
    { id: "13", en: "Dance party", it: "Festa da ballo" },
    { id: "14", en: "Dance performance", it: "Spettacolo di danza" },
    { id: "15", en: "Dinner show", it: "Dinner show" },
    { id: "16", en: "Fundraising fair", it: "Fiera di beneficenza" },
    { id: "17", en: "Party", it: "Festa" },
    { id: "18", en: "Festival", it: "Festival" },
    { id: "19", en: "Cycling tour", it: "Tour in bicicletta" },
    { id: "20", en: "Fundraising event", it: "Evento di raccolta fondi" },
    { id: "21", en: "Gala", it: "Gala" },
    { id: "22", en: "Lawnmower race", it: "Gara di tosaerba" },
    { id: "64", en: "Hospitality Vaart", it: "Ospitalità nautica" },
    { id: "23", en: "Huttenbouw’ (hut building event)", it: "Costruzione di capanne" },
    { id: "24", en: "Wedding party", it: "Festa di matrimonio" },
    { id: "25", en: "Ice rink", it: "Pista di pattinaggio" },
    { id: "26", en: "Incentive travel", it: "Viaggio incentive" },
    { id: "27", en: "Anniversary", it: "Anniversario" },
    { id: "28", en: "Christmas market", it: "Mercatino di Natale" },
    { id: "29", en: "Christmas market with ice rink", it: "Mercatino di Natale con pista" },
    { id: "30", en: "King's Day’ celebration", it: "Festa del Re" },
    { id: "31", en: "Lecture", it: "Conferenza/Lezione" },
    { id: "32", en: "Lustrum celebration", it: "Celebrazione del lustro" },
    { id: "33", en: "Market", it: "Mercato" },
    { id: "34", en: "Fashion show", it: "Sfilata di moda" },
    { id: "35", en: "Mud run / obstacle race", it: "Corsa nel fango / ostacoli" },
    { id: "36", en: "Open days", it: "Giornate a porte aperte" },
    { id: "37", en: "Horse riding event", it: "Evento equestre" },
    { id: "38", en: "Staff party", it: "Festa del personale" },
    { id: "39", en: "Private party", it: "Festa privata" },
    { id: "40", en: "Product launch", it: "Lancio del prodotto" },
    { id: "41", en: "Rally", it: "Rally" },
    { id: "42", en: "Business event", it: "Evento aziendale" },
    { id: "43", en: "Travel", it: "Viaggio" },
    { id: "44", en: "School activity", it: "Attività scolastica" },
    { id: "45", en: "Schützenfest’", it: "Festa dei tiratori" },
    { id: "46", en: "Seminar", it: "Seminario" },
    { id: "47", en: "Sinterklaas’ celebration", it: "Festa di San Nicola" },
    { id: "48", en: "Sports event", it: "Evento sportivo" },
    { id: "49", en: "Student party", it: "Festa studentesca" },
    { id: "50", en: "Exhibition", it: "Esposizione" },
    { id: "51", en: "Motor vehicle tour", it: "Tour veicoli a motore" },
    { id: "52", en: "Tractor pulling competition", it: "Gara di tractor pulling" },
    { id: "53", en: "Show", it: "Spettacolo" },
    { id: "54", en: "Hiking tour", it: "Escursione" },
    { id: "55", en: "Business trip", it: "Viaggio d'affari" },
    { id: "0", en: "Other", it: "Altro" }
];

export const countries = [
    { code: "nl", en: "Netherlands", it: "Paesi Bassi" },
    { code: "it", en: "Italy", it: "Italia" },
    { code: "be", en: "Belgium", it: "Belgio" },
    { code: "de", en: "Germany", it: "Germania" },
    { code: "fr", en: "France", it: "Francia" },
    { code: "es", en: "Spain", it: "Spagna" },
    // Simplified list for prototype, full list can be added later
];
